#define ORYX_CONFIGURATOR
#define ONESHOT_TAP_TOGGLE 4

#define PERMISSIVE_HOLD

#define TAPPING_FORCE_HOLD
#define IGNORE_MOD_TAP_INTERRUPT

#undef MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL 15

#undef MOUSEKEY_DELAY
#define MOUSEKEY_DELAY 5

// #undef MOUSEKEY_TIME_TO_MAX
// #define MOUSEKEY_TIME_TO_MAX 45

// #undef MOUSEKEY_WHEEL_MAX_SPEED
// #define MOUSEKEY_WHEEL_MAX_SPEED 3

#define AUTO_SHIFT_TIMEOUT 160
#define NO_AUTO_SHIFT_NUMERIC

#undef TAPPING_TERM
#define TAPPING_TERM 150

#undef DEBOUNCE_DELAY
#define DEBOUNCE_DELAY 5

#define COMBO_COUNT 1

// #define DYNAMIC_MACRO_USER_CALL
